#!/usr/bin/env python3
"""Çok zor sorular silindikten sonra havuzu dolduran kayıtlar.

Silinen 137 kaydın büyük kısmı **yıl ezberiydi**: dört yıl şıkkı olan bir
soru çoktan seçmelide elenemez, doğrudan tahmine düşer. Üç canla oynanan
ve varış sahnesiyle biten bir oyunda bu tür, oyuncuyu kendi hatası
olmadan eliyordu.

Buradaki sorular aynı konuları **olay, kişi ve kavram** üzerinden sorar.
"Karlofça hangi yılda imzalandı" yerine "Osmanlı'nın ilk kez toprak
kaybettiği antlaşma hangisidir": aynı bilgi, ama eleyerek cevaplanabilir.

Biçim: (zorluk, soru, doğru cevap, çeldirici, çeldirici, çeldirici)
"""

HISTORY = [
    ('easy', 'İstanbul’u fetheden Osmanlı padişahı hangi unvanla anılır?',
     'Fatih', 'Yavuz', 'Kanuni', 'Avcı'),
    ('easy', 'Türkiye Cumhuriyeti’nin kurucusu kimdir?',
     'Mustafa Kemal Atatürk', 'İsmet İnönü', 'Fevzi Çakmak',
     'Celâl Bayar'),
    ('easy', 'Türkiye Cumhuriyeti’nin ilk cumhurbaşkanı kimdir?',
     'Mustafa Kemal Atatürk', 'İsmet İnönü', 'Celâl Bayar',
     'Cemal Gürsel'),
    ('easy', 'Osmanlı Devleti’nin kurucusu kimdir?',
     'Osman Bey', 'Orhan Bey', 'Ertuğrul Gazi', 'Murad Hüdavendigâr'),
    ('easy', 'Kurtuluş Savaşı hangi ülkeye karşı başlatılan direnişle anılır?',
     'Yunanistan', 'Bulgaristan', 'Romanya', 'Sırbistan'),
    ('medium', 'Osmanlı’nın ilk başkenti neresidir?',
     'Söğüt', 'Bursa', 'Edirne', 'İstanbul'),
    ('medium', 'İstanbul’un fethinden önce Osmanlı’nın başkenti neresiydi?',
     'Edirne', 'Bursa', 'Söğüt', 'Konya'),
    ('medium', 'Osmanlı Devleti’nde ilk kez toprak kaybedilen antlaşma hangisidir?',
     'Karlofça', 'Pasarofça', 'Küçük Kaynarca', 'Ayastefanos'),
    ('medium', 'Lale Devri hangi antlaşmadan sonra başlamıştır?',
     'Pasarofça', 'Karlofça', 'Belgrad', 'Ziştovi'),
    ('medium', 'Tanzimat Fermanı’nın amacı neydi?',
     'Devlet düzenini yenilemek', 'Yeni topraklar almak',
     'Orduyu dağıtmak', 'Başkenti taşımak'),
    ('medium', 'Yeniçeri Ocağı’nın kaldırılması hangi adla anılır?',
     'Vaka-i Hayriye', 'Vaka-i Vakvakiye', 'Edirne Vakası',
     'Çınar Olayı'),
    ('medium', 'Kanuni Sultan Süleyman’a Avrupa’da verilen ad nedir?',
     'Muhteşem', 'Cesur', 'Bilge', 'Adil'),
    ('medium', 'Mimar Sinan hangi padişahlar döneminde baş mimarlık yaptı?',
     'Kanuni ve sonrası', 'Fatih dönemi', 'Osman Bey dönemi',
     'II. Mahmud dönemi'),
    ('medium', 'Piri Reis hangi alanda ünlüdür?',
     'Haritacılık', 'Mimarlık', 'Hekimlik', 'Şairlik'),
    ('medium', 'Evliya Çelebi’nin ünlü eseri hangisidir?',
     'Seyahatnâme', 'Divan-ı Lügati’t-Türk', 'Kutadgu Bilig',
     'Siyasetnâme'),
    ('medium', 'Katip Çelebi hangi alanda eser vermiştir?',
     'Coğrafya ve bibliyografya', 'Tıp', 'Matematik', 'Müzik'),
    ('easy', 'Türkiye Büyük Millet Meclisi hangi şehirde açılmıştır?',
     'Ankara', 'İstanbul', 'İzmir', 'Sivas'),
    ('medium', 'Sivas Kongresi’nin temel kararı neydi?',
     'Milli direnişi tek çatıda toplamak', 'Başkenti taşımak',
     'Orduyu terhis etmek', 'Saltanatı güçlendirmek'),
    ('medium', 'Cumhuriyet döneminde harf devrimiyle hangi alfabeye geçildi?',
     'Latin alfabesi', 'Kiril alfabesi', 'Yunan alfabesi',
     'Arap alfabesi'),
    ('medium', 'Millî Mücadele’nin deniz cephesindeki lojistik hattı hangisiydi?',
     'Karadeniz üzerinden İnebolu', 'Ege üzerinden İzmir',
     'Akdeniz üzerinden Mersin', 'Marmara üzerinden Gemlik'),
    ('easy', 'Birinci Dünya Savaşı’nda Osmanlı’nın savunduğu ünlü boğaz cephesi hangisidir?',
     'Çanakkale', 'Kafkas', 'Filistin', 'Galiçya'),
    ('medium', 'Çanakkale Savaşı hangi coğrafi geçidi korumak için yapıldı?',
     'Çanakkale Boğazı', 'İstanbul Boğazı', 'Süveyş Kanalı',
     'Cebelitarık Boğazı'),
    ('medium', 'Osmanlı’da devletin resmi tarih yazıcısına ne ad verilirdi?',
     'Vakanüvis', 'Nişancı', 'Defterdar', 'Reisülküttab'),
    ('medium', 'Osmanlı’da padişah fermanlarındaki imza niteliğindeki işaret nedir?',
     'Tuğra', 'Mühür', 'Berat', 'Tezkire'),
    ('medium', 'Divan-ı Hümayun neydi?',
     'Devletin en üst karar kurulu', 'Ordu birliği',
     'Vergi dairesi', 'Saray okulu'),
    ('medium', 'Osmanlı’da devşirme sistemiyle yetiştirilen ordu sınıfı hangisidir?',
     'Yeniçeriler', 'Akıncılar', 'Sipahiler', 'Azaplar'),
    ('medium', 'Enderun neydi?',
     'Sarayda devlet adamı yetiştiren okul', 'Askeri kışla',
     'Ticaret hanı', 'Vergi kalemi'),
    ('medium', 'İstanbul’un fethinde kullanılan devasa topları döken usta kimdir?',
     'Urban', 'Sinan', 'Davud Ağa', 'Hayreddin'),
    ('medium', 'Bizans İmparatorluğu’nun başkenti neresiydi?',
     'Konstantinopolis', 'Roma', 'Selanik', 'İzmit'),
    ('medium', 'Ayasofya’yı yaptıran Bizans imparatoru kimdir?',
     'I. Justinianos', 'Konstantin', 'Herakleios', 'Theodosius'),
    ('medium', 'Roma İmparatorluğu ikiye ayrıldığında doğu kısmının adı ne oldu?',
     'Bizans', 'Galya', 'Trakya', 'Frank Krallığı'),
    ('medium', 'Haçlı Seferleri’nin başlıca hedefi neresiydi?',
     'Kudüs', 'Roma', 'Kahire', 'Şam'),
    ('medium', 'Malazgirt Savaşı hangi iki güç arasında yapılmıştır?',
     'Selçuklular ile Bizans', 'Osmanlılar ile Bizans',
     'Selçuklular ile Memlükler', 'Osmanlılar ile Safeviler'),
    ('medium', 'Anadolu Selçuklu Devleti’nin başkenti neresiydi?',
     'Konya', 'Kayseri', 'Sivas', 'Erzurum'),
    ('medium', 'İlk Türk İslam devletlerinden Karahanlılar hangi alfabeyi kullandı?',
     'Arap alfabesi', 'Latin alfabesi', 'Kiril alfabesi',
     'Göktürk alfabesi'),
    ('medium', 'Orhun Yazıtları hangi alfabeyle yazılmıştır?',
     'Göktürk alfabesi', 'Uygur alfabesi', 'Arap alfabesi',
     'Latin alfabesi'),
    ('medium', 'Kutadgu Bilig’in yazarı kimdir?',
     'Yusuf Has Hacib', 'Kaşgarlı Mahmud', 'Ahmet Yesevi',
     'Edip Ahmet'),
    ('medium', 'Divanü Lugati’t-Türk’ün yazarı kimdir?',
     'Kaşgarlı Mahmud', 'Yusuf Has Hacib', 'Ali Şir Nevai',
     'Farabi'),
    ('medium', 'Osmanlı’da ilk matbaayı kuran kişi kimdir?',
     'İbrahim Müteferrika', 'Katip Çelebi', 'Evliya Çelebi',
     'Piri Reis'),
    ('medium', 'Osmanlı donanmasının ünlü amirali Barbaros’un asıl adı nedir?',
     'Hayreddin', 'Turgut', 'Kılıç Ali', 'Piyale'),
    ('medium', 'Preveze Deniz Zaferi hangi denizde kazanılmıştır?',
     'Akdeniz', 'Karadeniz', 'Kızıldeniz', 'Hint Okyanusu'),
    ('medium', 'Osmanlı’da tarım vergisiyle beslenen atlı asker sınıfı hangisidir?',
     'Tımarlı sipahi', 'Yeniçeri', 'Levent', 'Cebeci'),
    ('medium', 'Islahat Fermanı hangi konuda düzenleme getirdi?',
     'Gayrimüslimlerin hakları', 'Ordunun dağıtılması',
     'Başkentin taşınması', 'Paranın değiştirilmesi'),
    ('medium', 'Osmanlı’da ilk anayasa hangi adla bilinir?',
     'Kanun-i Esasi', 'Tanzimat Fermanı', 'Islahat Fermanı',
     'Sened-i İttifak'),
    ('medium', 'Lozan Antlaşması Türkiye için ne anlama gelir?',
     'Bağımsızlığın tanınması', 'Savaşın başlaması',
     'Toprak kaybı', 'Saltanatın kurulması'),
]

GENERAL = [
    ('easy', 'Bir günde kaç saat vardır?', '24', '12', '36', '48'),
    ('easy', 'Suyun donma sıcaklığı kaç derecedir?',
     '0', '10', '100', '-10'),
    ('easy', 'Gökkuşağında kaç renk sayılır?', '7', '5', '9', '3'),
    ('easy', 'İnsan vücudunda kanı pompalayan organ hangisidir?',
     'Kalp', 'Akciğer', 'Karaciğer', 'Böbrek'),
    ('easy', 'Bitkiler besin üretmek için hangi süreci kullanır?',
     'Fotosentez', 'Solunum', 'Terleme', 'Çimlenme'),
    ('easy', 'Dünya’nın uydusu hangisidir?',
     'Ay', 'Mars', 'Venüs', 'Titan'),
    ('easy', 'Güneş sistemindeki en büyük gezegen hangisidir?',
     'Jüpiter', 'Satürn', 'Dünya', 'Mars'),
    ('medium', 'Pusulanın gösterdiği yön hangisidir?',
     'Kuzey', 'Doğu', 'Batı', 'Güney'),
    ('medium', 'Deprem şiddetini ölçen aletin adı nedir?',
     'Sismograf', 'Barometre', 'Termometre', 'Higrometre'),
    ('medium', 'Hava basıncını ölçen alet hangisidir?',
     'Barometre', 'Sismograf', 'Ampermetre', 'Manometre'),
    ('medium', 'Sesin havada yayılması için neye ihtiyaç vardır?',
     'Ortam maddesi', 'Işık', 'Elektrik', 'Manyetik alan'),
    ('medium', 'Elektrik akımını ileten malzemelere ne ad verilir?',
     'İletken', 'Yalıtkan', 'Direnç', 'Kondansatör'),
    ('medium', 'Bir dikdörtgenin alanı nasıl bulunur?',
     'Kısa kenar ile uzun kenarın çarpımı', 'Kenarların toplamı',
     'Çevrenin yarısı', 'Köşegenin karesi'),
    ('medium', 'Üçgenin iç açıları toplamı kaç derecedir?',
     '180', '360', '90', '270'),
    ('medium', 'Bir sayının kendisiyle çarpımına ne ad verilir?',
     'Kare', 'Kök', 'Kat', 'Bölüm'),
    ('medium', 'Türkiye’nin para birimi nedir?',
     'Türk lirası', 'Euro', 'Dolar', 'Dinar'),
    ('medium', 'Enflasyon ne anlama gelir?',
     'Fiyatların genel artışı', 'Faizlerin düşmesi',
     'Üretimin artması', 'İşsizliğin azalması'),
    ('medium', 'İhracat ne anlama gelir?',
     'Yurt dışına mal satımı', 'Yurt dışından mal alımı',
     'Vergi toplama', 'Borçlanma'),
    ('medium', 'Bütçe nedir?',
     'Gelir ve gider planı', 'Borç listesi', 'Vergi oranı',
     'Faiz hesabı'),
    ('easy', 'Acil durumlarda aranan tek numara hangisidir?',
     '112', '155', '110', '156'),
    ('medium', 'Trafikte kırmızı ışık ne anlama gelir?',
     'Dur', 'Geç', 'Yavaşla', 'Hazırlan'),
    ('medium', 'Geri dönüşüm neyi amaçlar?',
     'Atıkları yeniden kullanmak', 'Atıkları yakmak',
     'Atıkları gömmek', 'Atıkları denize dökmek'),
    ('medium', 'Küresel ısınmanın başlıca nedeni nedir?',
     'Sera gazı salımı', 'Güneş tutulması', 'Deprem', 'Rüzgâr'),
    ('medium', 'Bir maratonun uzunluğu yaklaşık kaç kilometredir?',
     '42', '21', '10', '60'),
    ('medium', 'Olimpiyat oyunları kaç yılda bir düzenlenir?',
     'Dört', 'İki', 'Üç', 'Beş'),
]
