#!/usr/bin/env python3
"""Ulaşım kategorisinin elle yazılmış soruları.

Hepsi `model_knowledge` olarak işaretlidir: bağımsız kaynakla
doğrulanmadılar. Kaynak alanı sorunun ait olduğu kurumu gösterir, tek tek
doğrulandığını iddia etmez.
"""

IETT = 'https://www.iett.istanbul/'
TCDD = 'https://www.marmaray.gov.tr/'
METRO = 'https://www.metro.istanbul/'
KGM = 'https://www.kgm.gov.tr/'
SEHIRHAT = 'https://www.sehirhatlari.istanbul/'

# (soru, doğru, [çeldirici x3], zorluk, kaynak)
Q = [
 # --- Tarih ---
 ("İstanbul'daki Tünel, hangi yıl işletmeye açılmıştır?", "1875",
  ["1863", "1889", "1901"], "hard", IETT),
 ("Karaköy ile Beyoğlu arasında işleyen Tünel, ne tür bir hattır?",
  "Füniküler", ["Tramvay", "Teleferik", "Banliyö treni"], "medium", IETT),
 ("İstanbul'un ilk modern metro hattı hangi yıl açılmıştır?", "1989",
  ["1975", "1994", "2000"], "hard", METRO),
 ("Marmaray hangi yıl işletmeye açılmıştır?", "2013",
  ["2009", "2016", "2019"], "medium", TCDD),
 ("Marmaray'ın açılış tarihi hangi ulusal güne denk getirilmiştir?",
  "29 Ekim", ["23 Nisan", "19 Mayıs", "30 Ağustos"], "medium", TCDD),
 ("Marmaray'ın İstanbul Boğazı geçişi hangi yöntemle inşa edilmiştir?",
  "Batırma tüp tünel", ["Asma köprü", "Açık kazı", "Yüzer ponton"],
  "hard", TCDD),
 ("Avrasya Tüneli hangi yıl trafiğe açılmıştır?", "2016",
  ["2011", "2013", "2020"], "hard", KGM),
 ("Avrasya Tüneli hangi tür trafiğe hizmet eder?", "Karayolu",
  ["Demiryolu", "Yaya", "Metro"], "medium", KGM),
 ("İstanbul'da metrobüs işletmesi hangi yıl başlamıştır?", "2007",
  ["2001", "2004", "2011"], "medium", IETT),
 ("İstanbul Boğazı üzerindeki ilk asma köprü hangi yıl açılmıştır?",
  "1973", ["1968", "1981", "1988"], "medium", KGM),
 ("Fatih Sultan Mehmet Köprüsü hangi yıl hizmete girmiştir?", "1988",
  ["1973", "1994", "2004"], "medium", KGM),
 ("Yavuz Sultan Selim Köprüsü hangi yıl açılmıştır?", "2016",
  ["2009", "2013", "2019"], "medium", KGM),
 ("İstanbul'da atlı tramvay işletmesi hangi yüzyılda başlamıştır?",
  "19. yüzyıl", ["17. yüzyıl", "18. yüzyıl", "20. yüzyıl"], "hard", IETT),
 ("İstanbul'un Avrupa yakasındaki eski tramvay hattı hangi on yılda kapatılmıştır?",
  "1960'lar", ["1930'lar", "1940'lar", "1980'ler"], "hard", IETT),
 ("Nostaljik tramvayın işlediği İstiklal Caddesi hangi ilçededir?",
  "Beyoğlu", ["Fatih", "Şişli", "Beşiktaş"], "easy", IETT),

 # --- Sistemler ---
 ("Marmaray hattı hangi iki yakayı demiryoluyla birbirine bağlar?",
  "Avrupa ve Anadolu", ["Kuzey ve Güney", "Asya ve Afrika",
  "Trakya ve Ege"], "easy", TCDD),
 ("T1 tramvay hattının uçlarından biri Kabataş ise diğeri neresidir?",
  "Bağcılar", ["Eminönü", "Zeytinburnu", "Topkapı"], "medium", METRO),
 ("Taksim ile Kabataş arasında işleyen F1 hattı ne tür bir sistemdir?",
  "Füniküler", ["Tramvay", "Metro", "Teleferik"], "medium", METRO),
 ("Eyüp ile Piyerloti arasındaki hat ne tür bir sistemdir?", "Teleferik",
  ["Füniküler", "Tramvay", "Metro"], "medium", METRO),
 ("İstanbul'da şehir içi deniz ulaşımını yürüten köklü kuruluş hangisidir?",
  "Şehir Hatları", ["Devlet Demiryolları", "Karayolları", "Deniz Kuvvetleri"],
  "medium", SEHIRHAT),
 ("İstanbul'da otobüs işletmesini yürüten kurumun kısaltması nedir?",
  "İETT", ["TCDD", "KGM", "DHMİ"], "easy", IETT),
 ("İstanbul'da toplu ulaşımda kullanılan temassız kartın adı nedir?",
  "İstanbulkart", ["Akbil kart", "Şehirkart", "Mavikart"], "easy", IETT),
 ("Metrobüs hattı ağırlıklı olarak hangi güzergâh boyunca ilerler?",
  "D-100 karayolu", ["Sahil yolu", "TEM otoyolu", "Çevre yolu"],
  "medium", IETT),
 ("Haydarpaşa Garı İstanbul'un hangi yakasındadır?", "Anadolu",
  ["Avrupa", "Adalar", "Trakya"], "easy", TCDD),
 ("Sirkeci Garı tarihsel olarak hangi ünlü tren hattının son durağıydı?",
  "Orient Express", ["Trans-Sibirya", "Hicaz Demiryolu", "Bağdat Demiryolu"],
  "hard", TCDD),
 ("M2 hattının Haliç geçişi hangi yapı üzerinden sağlanır?",
  "Haliç Metro Köprüsü", ["Galata Köprüsü", "Atatürk Köprüsü",
  "Unkapanı Köprüsü"], "hard", METRO),
 ("İstanbul Havalimanı hangi metro hattıyla şehir merkezine bağlanır?",
  "M11", ["M1A", "M4", "M9"], "medium", METRO),
 ("Sabiha Gökçen Havalimanı hangi metro hattının ucundadır?", "M4",
  ["M5", "M8", "M2"], "easy", METRO),
 ("Atatürk Havalimanı hangi metro hattının ucundaydı?", "M1A",
  ["M1B", "M3", "M9"], "medium", METRO),
 ("Kadıköy ile Kartal arasını bağlayan metro hattı hangisidir?", "M4",
  ["M5", "M8", "M7"], "medium", METRO),
 ("Üsküdar'dan başlayan metro hattı hangisidir?", "M5",
  ["M4", "M8", "M2"], "medium", METRO),
 ("Türkiye'nin ilk sürücüsüz metro hattı hangisidir?", "M5",
  ["M1A", "M2", "M3"], "hard", METRO),
 ("Levent ile Boğaziçi Üniversitesi arasındaki kısa metro hattı hangisidir?",
  "M6", ["M2", "M7", "M9"], "medium", METRO),
 ("Mecidiyeköy'den geçen ve Mahmutbey'e uzanan metro hattı hangisidir?",
  "M7", ["M2", "M3", "M9"], "medium", METRO),
 ("Bostancı ile Parseller arasında işleyen metro hattı hangisidir?", "M8",
  ["M4", "M5", "M10"], "medium", METRO),
 ("Bakırköy ile Kayaşehir arasında işleyen metro hattı hangisidir?", "M3",
  ["M1B", "M9", "M7"], "medium", METRO),

 # --- Kavramlar ---
 ("Bir metro hattında iki tren arasındaki süreye ne ad verilir?", "Sefer aralığı",
  ["Sefer süresi", "Duraklama süresi", "Hat uzunluğu"], "medium", METRO),
 ("Raylı sistemlerde trenin akımı aldığı üstteki telin adı nedir?",
  "Katener", ["Ray", "Makas", "Sinyal"], "hard", TCDD),
 ("Demiryolunda trenin bir hattan diğerine geçmesini sağlayan düzenek nedir?",
  "Makas", ["Katener", "Balast", "Peron"], "medium", TCDD),
 ("İstasyonda yolcunun trene bindiği yükseltilmiş alana ne denir?", "Peron",
  ["Makas", "Gişe", "Katener"], "easy", METRO),
 ("İki hattın kesiştiği ve yolcunun hat değiştirdiği istasyona ne denir?",
  "Aktarma istasyonu", ["Son durak", "Ara durak", "Depo"],
  "easy", METRO),
 ("Trenlerin bakım ve gecelemesi için kullanılan tesise ne ad verilir?",
  "Depo", ["Peron", "Gişe", "Makas"], "medium", METRO),
 ("Raylı sistemde araçların altındaki tekerlek grubuna ne ad verilir?",
  "Boji", ["Pantograf", "Katener", "Balast"], "hard", TCDD),
 ("Elektrikli trenin katenerden akım almasını sağlayan parça nedir?",
  "Pantograf", ["Boji", "Makas", "Balast"], "hard", TCDD),
 ("Demiryolu traversleri altına serilen taş malzemeye ne denir?", "Balast",
  ["Boji", "Katener", "Pantograf"], "hard", TCDD),
 ("Metroda hattın tek yönde taşıyabileceği saatlik yolcu sayısına ne denir?",
  "Hat kapasitesi", ["Sefer sıklığı", "Doluluk oranı", "Yolculuk süresi"],
  "medium", METRO),

 # --- Dünya ---
 ("Dünyanın ilk metro hattı hangi şehirde açılmıştır?", "Londra",
  ["Paris", "New York", "Budapeşte"], "medium", 'https://tfl.gov.uk/'),
 ("Londra metrosu hangi yıl açılmıştır?", "1863",
  ["1875", "1890", "1900"], "hard", 'https://tfl.gov.uk/'),
 ("Paris metrosunun açılış yılı hangisidir?", "1900",
  ["1863", "1885", "1927"], "hard", 'https://www.ratp.fr/'),
 ("Londra metrosunun halk arasındaki adı nedir?", "The Tube",
  ["The Metro", "The Subway", "The Line"], "easy", 'https://tfl.gov.uk/'),
 ("New York'ta metro sistemi için hangi sözcük kullanılır?", "Subway",
  ["Tube", "Metro", "U-Bahn"], "easy", 'https://new.mta.info/'),
 ("Almanya'da şehir içi metro sistemleri hangi kısaltmayla anılır?",
  "U-Bahn", ["S-Bahn", "Tube", "RER"], "medium", 'https://www.bvg.de/'),
 ("Japonya'nın yüksek hızlı tren sistemi hangi adla bilinir?", "Shinkansen",
  ["Maglev", "Eurostar", "TGV"], "medium", 'https://www.jreast.co.jp/'),
 ("Fransa'nın yüksek hızlı tren sistemi hangi kısaltmayla anılır?", "TGV",
  ["ICE", "AVE", "HST"], "medium", 'https://www.sncf.com/'),
 ("Manş Tüneli hangi iki ülkeyi demiryoluyla bağlar?",
  "Birleşik Krallık ve Fransa", ["Fransa ve Belçika",
  "İspanya ve Fas", "İtalya ve İsviçre"], "medium",
  'https://www.eurotunnel.com/'),
 ("Türkiye'nin ilk yüksek hızlı tren hattı hangi iki şehri bağlamıştır?",
  "Ankara ve Eskişehir", ["İstanbul ve Ankara", "İzmir ve Manisa",
  "Konya ve Karaman"], "hard", TCDD),
]
